### ISSUE TITLE
Singularity happens sometimes in solve_interpolation

### ISSUE THREAD

**Issue by zwfcrazy** [sunniesuhyoung/DST#5]
Sometimes singularity happens when calling solve_interpolation.

Traceback (most recent call last):
  File "main.py", line 115, in <module>
    device=device)
  File "/root/DST/styletransfer.py", line 144, in DST
    new_im, content_im_warp, warp_field = apply_warp(new_im, [src_Kpts_aug], [dst_Kpts_aug], device, sharp=sharp_warp, im2=content_im_warp)
  File "/root/DST/warp.py", line 432, in apply_warp
    new_im, new_im2, warp_field = image_warp(new_im, dst, dst-src, device, sharp=sharp, img2=new_im2)
  File "/root/DST/warp.py", line 86, in image_warp
    w, v = solve_interpolation(dst_pts, flow_pts, device)
  File "/root/DST/warp.py", line 226, in solve_interpolation
    w_v, _ = torch.solve(rhs, lhs)
RuntimeError: solve_cuda: U(371,371) is zero, singular U.

I tested 10 image pairs, 2 of them got this error.

Update: this seems to be a random event. For the same pair of images, it may or may not happen.

**Comment by FDU-WeiXiZhang** [comment]
Same here.

**Comment by RazvanRotaru** [comment]
try deleting NBB and redownloading it. worked for me

**Comment by VladimirYugayKaia** [comment]
@FDU-WeiXiZhang did you manage to solve the problem? Always getting into the same issue 

@RazvanRotaru tried your solution, didn't really work for me

**Comment by jiangzuojifeng** [comment]
Same problem

**Comment by Bakko000** [comment]
Same problem.
